{
  "name": "SemanticModel",
  "compatibilityLevel": 1500,
  "model": {
    "culture": "fr-FR",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/LAPTOP-BILEL\\POC_MSSQL_BHN2;OLAP_AdventureWorksDW2019",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "LAPTOP-BILEL\\POC_MSSQL_BHN2",
            "database": "OLAP_AdventureWorksDW2019"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "Windows",
          "kind": "SQL",
          "path": "laptop-bilel\\poc_mssql_bhn2;OLAP_AdventureWorksDW2019",
          "Username": "balal",
          "EncryptConnection": false
        }
      },
      {
        "type": "structured",
        "name": "SQL/LAPTOP-BILEL\\POC_MMSQL_BHN3",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "LAPTOP-BILEL\\POC_MMSQL_BHN3"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "Windows",
          "kind": "SQL",
          "path": "laptop-bilel\\poc_mmsql_bhn3",
          "Username": "balal",
          "EncryptConnection": false
        }
      }
    ],
    "tables": [
      {
        "name": "DimDate",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "isKey": true,
            "sourceColumn": "FullDateAlternateKey"
          },
          {
            "name": "DayNumberOfWeek",
            "dataType": "int64",
            "sourceColumn": "DayNumberOfWeek"
          },
          {
            "name": "EnglishDayNameOfWeek",
            "dataType": "string",
            "sourceColumn": "EnglishDayNameOfWeek"
          },
          {
            "name": "DayNumberOfMonth",
            "dataType": "int64",
            "sourceColumn": "DayNumberOfMonth"
          },
          {
            "name": "DayNumberOfYear",
            "dataType": "int64",
            "sourceColumn": "DayNumberOfYear"
          },
          {
            "name": "WeekNumberOfYear",
            "dataType": "int64",
            "sourceColumn": "WeekNumberOfYear"
          },
          {
            "name": "EnglishMonthName",
            "dataType": "string",
            "sourceColumn": "EnglishMonthName"
          },
          {
            "name": "MonthNumberOfYear",
            "dataType": "int64",
            "sourceColumn": "MonthNumberOfYear"
          },
          {
            "name": "CalendarQuarter",
            "dataType": "int64",
            "sourceColumn": "CalendarQuarter"
          },
          {
            "name": "CalendarYear",
            "dataType": "int64",
            "sourceColumn": "CalendarYear"
          },
          {
            "name": "CalendarSemester",
            "dataType": "int64",
            "sourceColumn": "CalendarSemester"
          },
          {
            "name": "FiscalQuarter",
            "dataType": "int64",
            "sourceColumn": "FiscalQuarter"
          },
          {
            "name": "FiscalYear",
            "dataType": "int64",
            "sourceColumn": "FiscalYear"
          },
          {
            "name": "FiscalSemester",
            "dataType": "int64",
            "sourceColumn": "FiscalSemester"
          },
          {
            "type": "calculated",
            "name": "MonthCalendar",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "RIGHT(\" \" & FORMAT([MonthNumberOfYear],\"#0\"), 2) & \" - \" & [EnglishMonthName]"
          },
          {
            "type": "calculated",
            "name": "DayOfWeek",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "RIGHT(\" \" & FORMAT([DayNumberOfWeek],\"#0\"), 2) & \" - \" & [EnglishDayNameOfWeek]"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/LAPTOP-BILEL\\POC_MSSQL_BHN2;OLAP_AdventureWorksDW2019\",",
                "    dbo_DimDate = Source{[Schema=\"dbo\",Item=\"DimDate\"]}[Data],",
                "    #\"Colonnes supprimées\" = Table.RemoveColumns(dbo_DimDate,{\"SpanishDayNameOfWeek\", \"FrenchDayNameOfWeek\", \"SpanishMonthName\", \"FrenchMonthName\"})",
                "in",
                "    #\"Colonnes supprimées\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "DaysCurrentQuarterToDate",
            "expression": "COUNTROWS( DATESQTD( 'DimDate'[Date]))"
          },
          {
            "name": "DaysInCurrentQuarter",
            "expression": "COUNTROWS( DATESBETWEEN( 'DimDate'[Date], STARTOFQUARTER( LASTDATE('DimDate'[Date])), ENDOFQUARTER('DimDate'[Date])))"
          }
        ],
        "hierarchies": [
          {
            "name": "Calendar",
            "levels": [
              {
                "name": "CalendarYear",
                "ordinal": 0,
                "column": "CalendarYear"
              },
              {
                "name": "CalendarSemester",
                "ordinal": 1,
                "column": "CalendarSemester"
              },
              {
                "name": "CalendarQuarter",
                "ordinal": 2,
                "column": "CalendarQuarter"
              },
              {
                "name": "MonthCalendar",
                "ordinal": 3,
                "column": "MonthCalendar"
              },
              {
                "name": "DayNumberOfMonth",
                "ordinal": 4,
                "column": "DayNumberOfMonth"
              }
            ]
          },
          {
            "name": "Fiscal",
            "levels": [
              {
                "name": "FiscalYear",
                "ordinal": 0,
                "column": "FiscalYear"
              },
              {
                "name": "FiscalSemester",
                "ordinal": 1,
                "column": "FiscalSemester"
              },
              {
                "name": "FiscalQuarter",
                "ordinal": 2,
                "column": "FiscalQuarter"
              },
              {
                "name": "MonthCalendar",
                "ordinal": 3,
                "column": "MonthCalendar"
              },
              {
                "name": "DayNumberOfMonth",
                "ordinal": 4,
                "column": "DayNumberOfMonth"
              }
            ]
          },
          {
            "name": "ProductionCalendar",
            "levels": [
              {
                "name": "CalendarYear",
                "ordinal": 0,
                "column": "CalendarYear"
              },
              {
                "name": "WeekNumberOfYear",
                "ordinal": 1,
                "column": "WeekNumberOfYear"
              },
              {
                "name": "DayNumberOfWeek",
                "ordinal": 2,
                "column": "DayNumberOfWeek"
              }
            ]
          }
        ]
      },
      {
        "name": "DimProduct",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "ProductAlternateKey",
            "dataType": "string",
            "sourceColumn": "ProductAlternateKey"
          },
          {
            "name": "ProductSubcategoryKey",
            "dataType": "int64",
            "sourceColumn": "ProductSubcategoryKey"
          },
          {
            "name": "WeightUnitMeasureCode",
            "dataType": "string",
            "sourceColumn": "WeightUnitMeasureCode"
          },
          {
            "name": "SizeUnitMeasureCode",
            "dataType": "string",
            "sourceColumn": "SizeUnitMeasureCode"
          },
          {
            "name": "EnglishProductName",
            "dataType": "string",
            "sourceColumn": "EnglishProductName"
          },
          {
            "name": "StandardCost",
            "dataType": "decimal",
            "sourceColumn": "StandardCost"
          },
          {
            "name": "FinishedGoodsFlag",
            "dataType": "boolean",
            "sourceColumn": "FinishedGoodsFlag"
          },
          {
            "name": "Color",
            "dataType": "string",
            "sourceColumn": "Color"
          },
          {
            "name": "SafetyStockLevel",
            "dataType": "int64",
            "sourceColumn": "SafetyStockLevel"
          },
          {
            "name": "ReorderPoint",
            "dataType": "int64",
            "sourceColumn": "ReorderPoint"
          },
          {
            "name": "ListPrice",
            "dataType": "decimal",
            "sourceColumn": "ListPrice"
          },
          {
            "name": "Size",
            "dataType": "string",
            "sourceColumn": "Size"
          },
          {
            "name": "SizeRange",
            "dataType": "string",
            "sourceColumn": "SizeRange"
          },
          {
            "name": "Weight",
            "dataType": "double",
            "sourceColumn": "Weight"
          },
          {
            "name": "DaysToManufacture",
            "dataType": "int64",
            "sourceColumn": "DaysToManufacture"
          },
          {
            "name": "ProductLine",
            "dataType": "string",
            "sourceColumn": "ProductLine"
          },
          {
            "name": "DealerPrice",
            "dataType": "decimal",
            "sourceColumn": "DealerPrice"
          },
          {
            "name": "Class",
            "dataType": "string",
            "sourceColumn": "Class"
          },
          {
            "name": "Style",
            "dataType": "string",
            "sourceColumn": "Style"
          },
          {
            "name": "ModelName",
            "dataType": "string",
            "sourceColumn": "ModelName"
          },
          {
            "name": "EnglishDescription",
            "dataType": "string",
            "sourceColumn": "EnglishDescription"
          },
          {
            "name": "StartDate",
            "dataType": "dateTime",
            "sourceColumn": "StartDate"
          },
          {
            "name": "EndDate",
            "dataType": "dateTime",
            "sourceColumn": "EndDate"
          },
          {
            "name": "Status",
            "dataType": "string",
            "sourceColumn": "Status"
          },
          {
            "type": "calculated",
            "name": "ProductSubcategoryName",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "RELATED('DimProductSubcategory'[EnglishProductSubcategoryName])"
          },
          {
            "type": "calculated",
            "name": "ProductCategoryName",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "RELATED('DimProductCategory'[EnglishProductCategoryName])"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/LAPTOP-BILEL\\POC_MSSQL_BHN2;OLAP_AdventureWorksDW2019\",",
                "    dbo_DimProduct = Source{[Schema=\"dbo\",Item=\"DimProduct\"]}[Data],",
                "    #\"Colonnes supprimées\" = Table.RemoveColumns(dbo_DimProduct,{\"SpanishProductName\", \"FrenchProductName\", \"FrenchDescription\", \"ChineseDescription\", \"ArabicDescription\", \"HebrewDescription\", \"ThaiDescription\", \"GermanDescription\", \"JapaneseDescription\", \"TurkishDescription\"})",
                "in",
                "    #\"Colonnes supprimées\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Catégorie",
            "levels": [
              {
                "name": "Catégorie",
                "ordinal": 0,
                "column": "ProductCategoryName"
              },
              {
                "name": "Sous-catégorie",
                "ordinal": 1,
                "column": "ProductSubcategoryName"
              },
              {
                "name": "Modèle",
                "ordinal": 2,
                "column": "ModelName"
              },
              {
                "name": "Produit",
                "ordinal": 3,
                "column": "EnglishProductName"
              }
            ]
          }
        ]
      },
      {
        "name": "DimProductSubcategory",
        "columns": [
          {
            "name": "ProductSubcategoryKey",
            "dataType": "int64",
            "sourceColumn": "ProductSubcategoryKey"
          },
          {
            "name": "ProductSubcategoryAlternateKey",
            "dataType": "int64",
            "sourceColumn": "ProductSubcategoryAlternateKey"
          },
          {
            "name": "EnglishProductSubcategoryName",
            "dataType": "string",
            "sourceColumn": "EnglishProductSubcategoryName"
          },
          {
            "name": "ProductCategoryKey",
            "dataType": "int64",
            "sourceColumn": "ProductCategoryKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/LAPTOP-BILEL\\POC_MSSQL_BHN2;OLAP_AdventureWorksDW2019\",",
                "    dbo_DimProductSubcategory = Source{[Schema=\"dbo\",Item=\"DimProductSubcategory\"]}[Data],",
                "    #\"Colonnes supprimées\" = Table.RemoveColumns(dbo_DimProductSubcategory,{\"SpanishProductSubcategoryName\", \"FrenchProductSubcategoryName\"})",
                "in",
                "    #\"Colonnes supprimées\""
              ]
            }
          }
        ]
      },
      {
        "name": "FactInternetSales",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "OrderDateKey",
            "dataType": "int64",
            "sourceColumn": "OrderDateKey"
          },
          {
            "name": "DueDateKey",
            "dataType": "int64",
            "sourceColumn": "DueDateKey"
          },
          {
            "name": "ShipDateKey",
            "dataType": "int64",
            "sourceColumn": "ShipDateKey"
          },
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "PromotionKey",
            "dataType": "int64",
            "sourceColumn": "PromotionKey"
          },
          {
            "name": "CurrencyKey",
            "dataType": "int64",
            "sourceColumn": "CurrencyKey"
          },
          {
            "name": "SalesTerritoryKey",
            "dataType": "int64",
            "sourceColumn": "SalesTerritoryKey"
          },
          {
            "name": "SalesOrderNumber",
            "dataType": "string",
            "sourceColumn": "SalesOrderNumber"
          },
          {
            "name": "SalesOrderLineNumber",
            "dataType": "int64",
            "sourceColumn": "SalesOrderLineNumber"
          },
          {
            "name": "RevisionNumber",
            "dataType": "int64",
            "sourceColumn": "RevisionNumber"
          },
          {
            "name": "OrderQuantity",
            "dataType": "int64",
            "sourceColumn": "OrderQuantity"
          },
          {
            "name": "UnitPrice",
            "dataType": "decimal",
            "sourceColumn": "UnitPrice"
          },
          {
            "name": "ExtendedAmount",
            "dataType": "decimal",
            "sourceColumn": "ExtendedAmount"
          },
          {
            "name": "UnitPriceDiscountPct",
            "dataType": "double",
            "sourceColumn": "UnitPriceDiscountPct"
          },
          {
            "name": "DiscountAmount",
            "dataType": "double",
            "sourceColumn": "DiscountAmount"
          },
          {
            "name": "ProductStandardCost",
            "dataType": "decimal",
            "sourceColumn": "ProductStandardCost"
          },
          {
            "name": "TotalProductCost",
            "dataType": "decimal",
            "sourceColumn": "TotalProductCost"
          },
          {
            "name": "SalesAmount",
            "dataType": "decimal",
            "sourceColumn": "SalesAmount"
          },
          {
            "name": "TaxAmt",
            "dataType": "decimal",
            "sourceColumn": "TaxAmt"
          },
          {
            "name": "Freight",
            "dataType": "decimal",
            "sourceColumn": "Freight"
          },
          {
            "name": "CarrierTrackingNumber",
            "dataType": "string",
            "sourceColumn": "CarrierTrackingNumber"
          },
          {
            "name": "CustomerPONumber",
            "dataType": "string",
            "sourceColumn": "CustomerPONumber"
          },
          {
            "name": "OrderDate",
            "dataType": "dateTime",
            "sourceColumn": "OrderDate"
          },
          {
            "name": "DueDate",
            "dataType": "dateTime",
            "sourceColumn": "DueDate"
          },
          {
            "name": "ShipDate",
            "dataType": "dateTime",
            "sourceColumn": "ShipDate"
          },
          {
            "type": "calculated",
            "name": "Margin",
            "dataType": "decimal",
            "isDataTypeInferred": true,
            "expression": "[SalesAmount]-[TotalProductCost]",
            "formatString": "#,0.00 \"€\";-#,0.00 \"€\";#,0.00 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1036\" DisplayName=\"€ Français (France)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "FactInternetSales2010",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/LAPTOP-BILEL\\POC_MSSQL_BHN2;OLAP_AdventureWorksDW2019\",",
                "    dbo_FactInternetSales = Source{[Schema=\"dbo\",Item=\"FactInternetSales\"]}[Data],",
                "    #\"Lignes filtrées\" = Table.SelectRows(dbo_FactInternetSales, each [OrderDateKey] >= 20100101 and [OrderDateKey] <= 20101231)",
                "in",
                "    #\"Lignes filtrées\""
              ]
            }
          },
          {
            "name": "FactInternetSales2011",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/LAPTOP-BILEL\\POC_MSSQL_BHN2;OLAP_AdventureWorksDW2019\",",
                "    dbo_FactInternetSales = Source{[Schema=\"dbo\",Item=\"FactInternetSales\"]}[Data],",
                "    #\"Lignes filtrées\" = Table.SelectRows(dbo_FactInternetSales, each [OrderDateKey] >= 20110101 and [OrderDateKey] <= 20111231)",
                "in",
                "    #\"Lignes filtrées\""
              ]
            }
          },
          {
            "name": "FactInternetSales2012",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/LAPTOP-BILEL\\POC_MSSQL_BHN2;OLAP_AdventureWorksDW2019\",",
                "    dbo_FactInternetSales = Source{[Schema=\"dbo\",Item=\"FactInternetSales\"]}[Data],",
                "    #\"Lignes filtrées\" = Table.SelectRows(dbo_FactInternetSales, each [OrderDateKey] >= 20120101 and [OrderDateKey] <= 20121231)",
                "in",
                "    #\"Lignes filtrées\""
              ]
            }
          },
          {
            "name": "FactInternetSales2013",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/LAPTOP-BILEL\\POC_MSSQL_BHN2;OLAP_AdventureWorksDW2019\",",
                "    dbo_FactInternetSales = Source{[Schema=\"dbo\",Item=\"FactInternetSales\"]}[Data],",
                "    #\"Lignes filtrées\" = Table.SelectRows(dbo_FactInternetSales, each [OrderDateKey] >= 20130101 and [OrderDateKey] <= 20131231)",
                "in",
                "    #\"Lignes filtrées\""
              ]
            }
          },
          {
            "name": "FactInternetSales2014",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/LAPTOP-BILEL\\POC_MSSQL_BHN2;OLAP_AdventureWorksDW2019\",",
                "    dbo_FactInternetSales = Source{[Schema=\"dbo\",Item=\"FactInternetSales\"]}[Data],",
                "    #\"Lignes filtrées\" = Table.SelectRows(dbo_FactInternetSales, each [OrderDateKey] >= 20140101 and [OrderDateKey] <= 20141231)",
                "in",
                "    #\"Lignes filtrées\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "InternetDistinctCountSalesOrder",
            "expression": "DISTINCTCOUNT([SalesOrderNumber])"
          },
          {
            "name": "InternetOrderLinesCount",
            "expression": "COUNTA([SalesOrderLineNumber])"
          },
          {
            "name": "InternetTotalUnits",
            "expression": "SUM([OrderQuantity])"
          },
          {
            "name": "InternetTotalDiscountAmount",
            "expression": "SUM([DiscountAmount])"
          },
          {
            "name": "InternetTotalProductCost",
            "expression": "SUM([TotalProductCost])"
          },
          {
            "name": "InternetTotalSales",
            "expression": "SUM([SalesAmount])"
          },
          {
            "name": "InternetTotalMargin",
            "expression": "SUM([Margin])"
          },
          {
            "name": "InternetTotalTaxAmt",
            "expression": "SUM([TaxAmt])"
          },
          {
            "name": "InternetTotalFreight",
            "expression": "SUM([Freight])"
          },
          {
            "name": "InternetPreviousQuarterMargin",
            "expression": "CALCULATE([InternetTotalMargin],PREVIOUSQUARTER('DimDate'[Date]))"
          },
          {
            "name": "InternetCurrentQuarterMargin",
            "expression": "TOTALQTD([InternetTotalMargin],'DimDate'[Date])"
          },
          {
            "name": "InternetPreviousQuarterMarginProportionToQTD",
            "expression": "[InternetPreviousQuarterMargin]*([DaysCurrentQuarterToDate]/[DaysInCurrentQuarter])"
          },
          {
            "name": "InternetPreviousQuarterSales",
            "expression": "CALCULATE([InternetTotalSales],PREVIOUSQUARTER('DimDate'[Date]))"
          },
          {
            "name": "InternetCurrentQuarterSales",
            "expression": "TOTALQTD([InternetTotalSales],'DimDate'[Date])"
          },
          {
            "name": "InternetPreviousQuarterSalesProportionToQTD",
            "expression": "[InternetPreviousQuarterSales]*([DaysCurrentQuarterToDate]/[DaysInCurrentQuarter])"
          },
          {
            "name": "InternetCurrentQuarterSalesPerformance",
            "expression": "IF([InternetPreviousQuarterSalesProportionToQTD]<>0,([InternetCurrentQuarterSales]-[InternetPreviousQuarterSalesProportionToQTD])/[InternetPreviousQuarterSalesProportionToQTD],BLANK())",
            "kpi": {
              "targetExpression": "1,1",
              "statusGraphic": "Shapes",
              "statusExpression": [
                "var x='FactInternetSales'[InternetCurrentQuarterSalesPerformance] return",
                "            if(ISBLANK(x),BLANK(),",
                "                    If(x<1,-1,",
                "\t                If(x<1.07,0,1)",
                "                )",
                "            )",
                "            "
              ],
              "annotations": [
                {
                  "name": "GoalType",
                  "value": "StaticValue"
                },
                {
                  "name": "KpiStatusType",
                  "value": "Linear"
                },
                {
                  "name": "KpiThresholdType",
                  "value": "Absolute"
                },
                {
                  "name": "KpiThresholdOrdering",
                  "value": "Ascending"
                },
                {
                  "name": "KpiThresholdCount",
                  "value": "2"
                },
                {
                  "name": "KpiThreshold_0",
                  "value": "1"
                },
                {
                  "name": "KpiThreshold_1",
                  "value": "1.07"
                }
              ]
            }
          },
          {
            "name": "InternetCurrentQuarterMarginPerformance",
            "expression": "IF([InternetPreviousQuarterMarginProportionToQTD]<>0,([InternetCurrentQuarterMargin]-[InternetPreviousQuarterMarginProportionToQTD])/[InternetPreviousQuarterMarginProportionToQTD],BLANK())",
            "kpi": {
              "targetExpression": "1,25",
              "statusGraphic": "Shapes",
              "statusExpression": [
                "var x='FactInternetSales'[InternetCurrentQuarterMarginPerformance] return",
                "            if(ISBLANK(x),BLANK(),",
                "                    If(x<0.8,-1,",
                "\t                If(x<1.03,0,1)",
                "                )",
                "            )",
                "            "
              ],
              "annotations": [
                {
                  "name": "GoalType",
                  "value": "StaticValue"
                },
                {
                  "name": "KpiStatusType",
                  "value": "Linear"
                },
                {
                  "name": "KpiThresholdType",
                  "value": "Absolute"
                },
                {
                  "name": "KpiThresholdOrdering",
                  "value": "Ascending"
                },
                {
                  "name": "KpiThresholdCount",
                  "value": "2"
                },
                {
                  "name": "KpiThreshold_0",
                  "value": "0.8"
                },
                {
                  "name": "KpiThreshold_1",
                  "value": "1.03"
                }
              ]
            }
          }
        ]
      },
      {
        "name": "DimCustomer",
        "columns": [
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "GeographyKey",
            "dataType": "int64",
            "sourceColumn": "GeographyKey"
          },
          {
            "name": "CustomerAlternateKey",
            "dataType": "string",
            "sourceColumn": "CustomerAlternateKey"
          },
          {
            "name": "Title",
            "dataType": "string",
            "sourceColumn": "Title"
          },
          {
            "name": "FirstName",
            "dataType": "string",
            "sourceColumn": "FirstName"
          },
          {
            "name": "MiddleName",
            "dataType": "string",
            "sourceColumn": "MiddleName"
          },
          {
            "name": "LastName",
            "dataType": "string",
            "sourceColumn": "LastName"
          },
          {
            "name": "NameStyle",
            "dataType": "boolean",
            "sourceColumn": "NameStyle"
          },
          {
            "name": "BirthDate",
            "dataType": "dateTime",
            "sourceColumn": "BirthDate"
          },
          {
            "name": "MaritalStatus",
            "dataType": "string",
            "sourceColumn": "MaritalStatus"
          },
          {
            "name": "Suffix",
            "dataType": "string",
            "sourceColumn": "Suffix"
          },
          {
            "name": "Gender",
            "dataType": "string",
            "sourceColumn": "Gender"
          },
          {
            "name": "EmailAddress",
            "dataType": "string",
            "sourceColumn": "EmailAddress"
          },
          {
            "name": "YearlyIncome",
            "dataType": "decimal",
            "sourceColumn": "YearlyIncome"
          },
          {
            "name": "TotalChildren",
            "dataType": "int64",
            "sourceColumn": "TotalChildren"
          },
          {
            "name": "NumberChildrenAtHome",
            "dataType": "int64",
            "sourceColumn": "NumberChildrenAtHome"
          },
          {
            "name": "EnglishEducation",
            "dataType": "string",
            "sourceColumn": "EnglishEducation"
          },
          {
            "name": "SpanishEducation",
            "dataType": "string",
            "sourceColumn": "SpanishEducation"
          },
          {
            "name": "FrenchEducation",
            "dataType": "string",
            "sourceColumn": "FrenchEducation"
          },
          {
            "name": "EnglishOccupation",
            "dataType": "string",
            "sourceColumn": "EnglishOccupation"
          },
          {
            "name": "SpanishOccupation",
            "dataType": "string",
            "sourceColumn": "SpanishOccupation"
          },
          {
            "name": "FrenchOccupation",
            "dataType": "string",
            "sourceColumn": "FrenchOccupation"
          },
          {
            "name": "HouseOwnerFlag",
            "dataType": "string",
            "sourceColumn": "HouseOwnerFlag"
          },
          {
            "name": "NumberCarsOwned",
            "dataType": "int64",
            "sourceColumn": "NumberCarsOwned"
          },
          {
            "name": "AddressLine1",
            "dataType": "string",
            "sourceColumn": "AddressLine1"
          },
          {
            "name": "AddressLine2",
            "dataType": "string",
            "sourceColumn": "AddressLine2"
          },
          {
            "name": "Phone",
            "dataType": "string",
            "sourceColumn": "Phone"
          },
          {
            "name": "DateFirstPurchase",
            "dataType": "dateTime",
            "sourceColumn": "DateFirstPurchase"
          },
          {
            "name": "CommuteDistance",
            "dataType": "string",
            "sourceColumn": "CommuteDistance"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/LAPTOP-BILEL\\POC_MSSQL_BHN2;OLAP_AdventureWorksDW2019\",",
                "    dbo_DimCustomer = Source{[Schema=\"dbo\",Item=\"DimCustomer\"]}[Data]",
                "in",
                "    dbo_DimCustomer"
              ]
            }
          }
        ]
      },
      {
        "name": "DimGeography",
        "columns": [
          {
            "name": "GeographyKey",
            "dataType": "int64",
            "sourceColumn": "GeographyKey"
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City"
          },
          {
            "name": "StateProvinceCode",
            "dataType": "string",
            "sourceColumn": "StateProvinceCode"
          },
          {
            "name": "StateProvinceName",
            "dataType": "string",
            "sourceColumn": "StateProvinceName"
          },
          {
            "name": "CountryRegionCode",
            "dataType": "string",
            "sourceColumn": "CountryRegionCode"
          },
          {
            "name": "EnglishCountryRegionName",
            "dataType": "string",
            "sourceColumn": "EnglishCountryRegionName"
          },
          {
            "name": "PostalCode",
            "dataType": "string",
            "sourceColumn": "PostalCode"
          },
          {
            "name": "SalesTerritoryKey",
            "dataType": "int64",
            "sourceColumn": "SalesTerritoryKey"
          },
          {
            "name": "IpAddressLocator",
            "dataType": "string",
            "sourceColumn": "IpAddressLocator"
          },
          {
            "type": "calculated",
            "name": "ContinentName",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "IF('DimGeography'[EnglishCountryRegionName]=\"United States\" || DimGeography[EnglishCountryRegionName]=\"Canada\",\"North America\",IF(DimGeography[EnglishCountryRegionName]=\"Australia\",\"Pacific\",\"Europe\"))"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/LAPTOP-BILEL\\POC_MSSQL_BHN2;OLAP_AdventureWorksDW2019\",",
                "    dbo_DimGeography = Source{[Schema=\"dbo\",Item=\"DimGeography\"]}[Data]",
                "in",
                "    dbo_DimGeography"
              ]
            }
          }
        ]
      },
      {
        "name": "DimProductCategory",
        "columns": [
          {
            "name": "ProductCategoryKey",
            "dataType": "int64",
            "sourceColumn": "ProductCategoryKey"
          },
          {
            "name": "ProductCategoryAlternateKey",
            "dataType": "int64",
            "sourceColumn": "ProductCategoryAlternateKey"
          },
          {
            "name": "EnglishProductCategoryName",
            "dataType": "string",
            "sourceColumn": "EnglishProductCategoryName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/LAPTOP-BILEL\\POC_MSSQL_BHN2;OLAP_AdventureWorksDW2019\",",
                "    dbo_DimProductCategory = Source{[Schema=\"dbo\",Item=\"DimProductCategory\"]}[Data]",
                "in",
                "    dbo_DimProductCategory"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "76c3d8a1-1a21-429d-ad5f-5460728bc1c8",
        "fromTable": "DimProduct",
        "fromColumn": "ProductSubcategoryKey",
        "toTable": "DimProductSubcategory",
        "toColumn": "ProductSubcategoryKey"
      },
      {
        "name": "0a88b829-f2a6-444b-9a3b-d03b05c303be",
        "fromTable": "FactInternetSales",
        "fromColumn": "CustomerKey",
        "toTable": "DimCustomer",
        "toColumn": "CustomerKey"
      },
      {
        "name": "47a9c076-8b37-4fb9-8d8f-a93fcbb17358",
        "fromTable": "FactInternetSales",
        "fromColumn": "ProductKey",
        "toTable": "DimProduct",
        "toColumn": "ProductKey"
      },
      {
        "name": "0e60e350-495a-43a8-a4b9-2a2a4f8a30f9",
        "fromTable": "FactInternetSales",
        "fromColumn": "OrderDate",
        "toTable": "DimDate",
        "toColumn": "Date"
      },
      {
        "name": "7104f2d0-fc3f-4650-8b95-7d45bae20174",
        "fromTable": "FactInternetSales",
        "fromColumn": "DueDate",
        "toTable": "DimDate",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "96986600-e90c-4191-8f6b-8ae7fca854c6",
        "fromTable": "FactInternetSales",
        "fromColumn": "ShipDate",
        "toTable": "DimDate",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "6745b21f-ce5d-4be1-bfd0-2535a8301c56",
        "fromTable": "DimCustomer",
        "fromColumn": "GeographyKey",
        "toTable": "DimGeography",
        "toColumn": "GeographyKey"
      },
      {
        "name": "274cdb08-2854-4fab-8fb4-092532fff595",
        "fromTable": "DimProductSubcategory",
        "fromColumn": "ProductCategoryKey",
        "toTable": "DimProductCategory",
        "toColumn": "ProductCategoryKey"
      }
    ],
    "perspectives": [
      {
        "name": "Ventes sur Internet",
        "tables": [
          {
            "name": "DimDate",
            "columns": [
              {
                "name": "CalendarQuarter"
              },
              {
                "name": "CalendarSemester"
              },
              {
                "name": "CalendarYear"
              },
              {
                "name": "Date"
              },
              {
                "name": "DateKey"
              },
              {
                "name": "DayNumberOfMonth"
              },
              {
                "name": "DayNumberOfWeek"
              },
              {
                "name": "DayNumberOfYear"
              },
              {
                "name": "DayOfWeek"
              },
              {
                "name": "EnglishDayNameOfWeek"
              },
              {
                "name": "EnglishMonthName"
              },
              {
                "name": "FiscalQuarter"
              },
              {
                "name": "FiscalSemester"
              },
              {
                "name": "FiscalYear"
              },
              {
                "name": "MonthCalendar"
              },
              {
                "name": "MonthNumberOfYear"
              },
              {
                "name": "WeekNumberOfYear"
              }
            ],
            "hierarchies": [
              {
                "name": "Calendar"
              },
              {
                "name": "Fiscal"
              },
              {
                "name": "ProductionCalendar"
              }
            ],
            "measures": [
              {
                "name": "DaysCurrentQuarterToDate"
              },
              {
                "name": "DaysInCurrentQuarter"
              }
            ]
          },
          {
            "name": "DimProduct",
            "columns": [
              {
                "name": "Class"
              },
              {
                "name": "Color"
              },
              {
                "name": "DaysToManufacture"
              },
              {
                "name": "DealerPrice"
              },
              {
                "name": "EndDate"
              },
              {
                "name": "EnglishDescription"
              },
              {
                "name": "EnglishProductName"
              },
              {
                "name": "FinishedGoodsFlag"
              },
              {
                "name": "ListPrice"
              },
              {
                "name": "ModelName"
              },
              {
                "name": "ProductAlternateKey"
              },
              {
                "name": "ProductCategoryName"
              },
              {
                "name": "ProductKey"
              },
              {
                "name": "ProductLine"
              },
              {
                "name": "ProductSubcategoryKey"
              },
              {
                "name": "ProductSubcategoryName"
              },
              {
                "name": "ReorderPoint"
              },
              {
                "name": "SafetyStockLevel"
              },
              {
                "name": "Size"
              },
              {
                "name": "SizeRange"
              },
              {
                "name": "SizeUnitMeasureCode"
              },
              {
                "name": "StandardCost"
              },
              {
                "name": "StartDate"
              },
              {
                "name": "Status"
              },
              {
                "name": "Style"
              },
              {
                "name": "Weight"
              },
              {
                "name": "WeightUnitMeasureCode"
              }
            ],
            "hierarchies": [
              {
                "name": "Catégorie"
              }
            ]
          },
          {
            "name": "DimProductSubcategory",
            "columns": [
              {
                "name": "EnglishProductSubcategoryName"
              },
              {
                "name": "ProductCategoryKey"
              },
              {
                "name": "ProductSubcategoryAlternateKey"
              },
              {
                "name": "ProductSubcategoryKey"
              }
            ]
          },
          {
            "name": "FactInternetSales",
            "columns": [
              {
                "name": "ProductKey"
              },
              {
                "name": "OrderDateKey"
              },
              {
                "name": "DueDateKey"
              },
              {
                "name": "ShipDateKey"
              },
              {
                "name": "CustomerKey"
              },
              {
                "name": "PromotionKey"
              },
              {
                "name": "CurrencyKey"
              },
              {
                "name": "SalesTerritoryKey"
              },
              {
                "name": "SalesOrderNumber"
              },
              {
                "name": "SalesOrderLineNumber"
              },
              {
                "name": "RevisionNumber"
              },
              {
                "name": "OrderQuantity"
              },
              {
                "name": "UnitPrice"
              },
              {
                "name": "ExtendedAmount"
              },
              {
                "name": "UnitPriceDiscountPct"
              },
              {
                "name": "DiscountAmount"
              },
              {
                "name": "ProductStandardCost"
              },
              {
                "name": "TotalProductCost"
              },
              {
                "name": "SalesAmount"
              },
              {
                "name": "TaxAmt"
              },
              {
                "name": "Freight"
              },
              {
                "name": "CarrierTrackingNumber"
              },
              {
                "name": "CustomerPONumber"
              },
              {
                "name": "OrderDate"
              },
              {
                "name": "DueDate"
              },
              {
                "name": "ShipDate"
              },
              {
                "name": "Margin"
              }
            ],
            "measures": [
              {
                "name": "InternetDistinctCountSalesOrder"
              },
              {
                "name": "InternetOrderLinesCount"
              },
              {
                "name": "InternetTotalUnits"
              },
              {
                "name": "InternetTotalDiscountAmount"
              },
              {
                "name": "InternetTotalProductCost"
              },
              {
                "name": "InternetTotalSales"
              },
              {
                "name": "InternetTotalMargin"
              },
              {
                "name": "InternetTotalTaxAmt"
              },
              {
                "name": "InternetTotalFreight"
              },
              {
                "name": "InternetPreviousQuarterMargin"
              },
              {
                "name": "InternetCurrentQuarterMargin"
              },
              {
                "name": "InternetPreviousQuarterMarginProportionToQTD"
              },
              {
                "name": "InternetPreviousQuarterSales"
              },
              {
                "name": "InternetCurrentQuarterSales"
              },
              {
                "name": "InternetPreviousQuarterSalesProportionToQTD"
              }
            ]
          },
          {
            "name": "DimCustomer",
            "columns": [
              {
                "name": "CustomerKey"
              },
              {
                "name": "GeographyKey"
              },
              {
                "name": "CustomerAlternateKey"
              },
              {
                "name": "Title"
              },
              {
                "name": "FirstName"
              },
              {
                "name": "MiddleName"
              },
              {
                "name": "LastName"
              },
              {
                "name": "NameStyle"
              },
              {
                "name": "BirthDate"
              },
              {
                "name": "MaritalStatus"
              },
              {
                "name": "Suffix"
              },
              {
                "name": "Gender"
              },
              {
                "name": "EmailAddress"
              },
              {
                "name": "YearlyIncome"
              },
              {
                "name": "TotalChildren"
              },
              {
                "name": "NumberChildrenAtHome"
              },
              {
                "name": "EnglishEducation"
              },
              {
                "name": "SpanishEducation"
              },
              {
                "name": "FrenchEducation"
              },
              {
                "name": "EnglishOccupation"
              },
              {
                "name": "SpanishOccupation"
              },
              {
                "name": "FrenchOccupation"
              },
              {
                "name": "HouseOwnerFlag"
              },
              {
                "name": "NumberCarsOwned"
              },
              {
                "name": "AddressLine1"
              },
              {
                "name": "AddressLine2"
              },
              {
                "name": "Phone"
              },
              {
                "name": "DateFirstPurchase"
              },
              {
                "name": "CommuteDistance"
              }
            ]
          },
          {
            "name": "DimGeography",
            "columns": [
              {
                "name": "GeographyKey"
              },
              {
                "name": "City"
              },
              {
                "name": "StateProvinceCode"
              },
              {
                "name": "StateProvinceName"
              },
              {
                "name": "CountryRegionCode"
              },
              {
                "name": "EnglishCountryRegionName"
              },
              {
                "name": "PostalCode"
              },
              {
                "name": "SalesTerritoryKey"
              },
              {
                "name": "IpAddressLocator"
              },
              {
                "name": "ContinentName"
              }
            ]
          },
          {
            "name": "DimProductCategory",
            "columns": [
              {
                "name": "ProductCategoryKey"
              },
              {
                "name": "ProductCategoryAlternateKey"
              },
              {
                "name": "EnglishProductCategoryName"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "Sales Manager",
        "modelPermission": "read"
      },
      {
        "name": "Sales Analyst US",
        "modelPermission": "read"
      },
      {
        "name": "Administrator",
        "modelPermission": "administrator",
        "members": [
          {
            "memberName": "Administrateur",
            "memberId": "S-1-5-21-2542261692-582263725-2587847945-500"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "600"
      }
    ]
  },
  "id": "SemanticModel"
}